-- Insert Session Commander Architecture Guide
INSERT INTO vault_modules (
  user_id, title, slug, description, domain, module_type, language, tags, code,
  why_it_matters, usage_hint, code_example, source_project, validation_status,
  visibility, difficulty, estimated_minutes, module_group, implementation_order,
  related_modules, solves_problems, common_errors, test_code, context_markdown,
  ai_metadata
) VALUES (
  '82f6649d-f8d6-4da3-9704-d69b2f37d1a1',
  'Session Commander Architecture Guide — Unified Session Coordination System',
  'session-commander-architecture-guide',
  'Architecture guide explaining how the 5 components of the Session Commander system (Coordinator, SessionMonitor, RetryStrategy, Feedback, Types) integrate into a unified session resilience architecture.',
  'architecture',
  'architecture_doc',
  'typescript',
  ARRAY['session-commander','architecture-guide','session-management','refresh-coordination','resilience','deduplication','exponential-backoff','visibility-api','event-driven'],
  E'/**\n * Session Commander Architecture Guide\n *\n * SYSTEM OVERVIEW:\n * The Session Commander is the SINGLE POINT OF CONTROL for all session-related\n * operations in a SaaS application. It replaces fragmented refresh logic\n * with a centralized, event-driven coordination system.\n *\n * COMPONENT MAP (5 files):\n *\n * SessionCommander (index.ts) — Singleton facade\n *   ├── RefreshCoordinator (coordinator.ts) — Deduplication + retry + backend call\n *   ├── SessionMonitor (session-monitor.ts) — visibilitychange + online + focus + adaptive intervals\n *   ├── RetryStrategy (retry-strategy.ts) — Exponential backoff + jitter + sleep + tabId\n *   ├── Feedback (feedback.ts) — Reconnecting/reconnected/expired toasts via Sonner\n *   └── Types (types.ts) — RefreshResult, CommanderState, SessionHealth, Config\n *\n * DATA FLOW:\n * 1. SessionMonitor detects event (tab visible, online, focus)\n * 2. SessionMonitor calls onCheck callback\n * 3. onCheck triggers SessionCommander.requestRefresh()\n * 4. SessionCommander delegates to RefreshCoordinator\n * 5. RefreshCoordinator deduplicates (returns existing Promise if active)\n * 6. RefreshCoordinator calls backend with AbortController timeout\n * 7. Backend returns: success | wait | unauthorized | error\n * 8. On wait: sleep(retryAfter), retry without incrementing attempt\n * 9. On error: getExponentialDelay(), retry\n * 10. On success/final failure: Feedback shows appropriate toast\n *\n * DEDUPLICATION: Multiple callers → same Promise via refreshQueue field\n * SERVER COORDINATION: Backend returns wait+retryAfter when another tab holds lock\n */\n\nimport { sessionCommander } from ''@/lib/session-commander'';\n\n// Start monitoring (typically in AuthProvider useEffect)\nsessionCommander.startMonitoring(() => {\n  const tokenContext = getTokenContext();\n  if (needsRefresh(tokenContext)) {\n    sessionCommander.requestRefresh();\n  }\n});\n\n// Request refresh from anywhere (deduplicated)\nconst result = await sessionCommander.requestRefresh();\nif (!result.success && result.reason === ''expired'') {\n  redirectToLogin();\n}\n\n// Cleanup\nsessionCommander.stopMonitoring();',
  'Session management is the most fragile part of any SaaS application. Without centralized coordination, you get race conditions (multiple tabs refreshing simultaneously), thundering herd problems, and poor UX (no feedback during reconnection). The Session Commander architecture eliminates ALL of these with a composable system handling deduplication, server-side locking, exponential backoff with jitter, and visual feedback — all in ~500 lines across 5 focused files.',
  'Use when building any SaaS with JWT/cookie-based auth needing multi-tab support, network interruption handling, background tab throttling, and session expiration. Implement all 5 components together. Pairs with token-manager-architecture-guide.',
  E'// In your AuthProvider:\nimport { sessionCommander } from ''@/lib/session-commander'';\nimport { needsRefresh, getTokenContext } from ''@/lib/token-manager'';\n\nuseEffect(() => {\n  sessionCommander.startMonitoring(() => {\n    const ctx = getTokenContext();\n    if (needsRefresh(ctx)) {\n      sessionCommander.requestRefresh();\n    }\n  });\n  return () => sessionCommander.stopMonitoring();\n}, []);\n\n// In your API client interceptor:\nif (response.status === 401) {\n  const result = await sessionCommander.requestRefresh();\n  if (result.success) return retryRequest();\n  throw new SessionExpiredError();\n}',
  'risecheckout',
  'validated',
  'global',
  'advanced',
  120,
  'session-commander',
  0,
  ARRAY['aab502c7-22a2-4d44-8b96-2d01cf5e8a67','4c02c917-bc31-4040-9350-963ea9d73f45','19f2c74a-4612-471c-b26d-4ec2bd329628']::uuid[],
  ARRAY['multiple tabs refreshing simultaneously','thundering herd on network recovery','no feedback during session reconnection','background tab throttling breaks heartbeat','race condition between refresh and API calls','how to coordinate session refresh across components'],
  '[{"error":"TypeError: Cannot read properties of null (reading requestRefresh)","cause":"SessionCommander singleton not initialized","fix":"Import from @/lib/session-commander barrel export"},{"error":"Multiple toasts for same reconnection","cause":"Feedback called without isShowingFeedback check","fix":"Let RefreshCoordinator manage feedback state internally"},{"error":"Infinite refresh loop on 401","cause":"API interceptor retries but gets another 401","fix":"Mark request as already-retried with header flag"}]'::jsonb,
  E'const p1 = sessionCommander.requestRefresh();\nconst p2 = sessionCommander.requestRefresh();\nassert(p1 === p2, ''Same promise for concurrent calls'');\nsessionCommander.startMonitoring(() => {});\nassert(sessionCommander.isRefreshing() === false);\nsessionCommander.stopMonitoring();',
  E'## Overview\n\nThe Session Commander is a centralized session coordination system for SaaS applications with cookie-based authentication. It replaces the anti-pattern of scattering refresh logic across API interceptors, timers, and auth providers.\n\n## How it Works\n\n5 files, each with single responsibility:\n1. **SessionCommander** (index.ts) — Singleton facade. requestRefresh(), startMonitoring(), stopMonitoring().\n2. **RefreshCoordinator** (coordinator.ts) — Deduplication engine. Stores active Promise in refreshQueue. Handles retry with exponential backoff.\n3. **SessionMonitor** (session-monitor.ts) — Event-driven monitor. visibilitychange, online, focus events. Adaptive intervals (1min foreground, 5min background).\n4. **RetryStrategy** (retry-strategy.ts) — Pure functions for exponential backoff with ±25% jitter.\n5. **Feedback** (feedback.ts) — Visual notifications via Sonner toasts.\n\n## When to Use\n- Any SaaS with JWT or cookie-based auth\n- Multi-tab applications\n- Applications needing graceful network interruption handling\n\n## When NOT to Use\n- Static sites without authentication\n- Server-rendered applications (SSR)\n- Applications with very short-lived tokens (<5 min)\n\n## Security Considerations\n- No secrets sent to backend — only cookies via credentials: include\n- Cloudflare Worker gateway injects API key server-side\n- AbortController enforces 15s request timeout',
  '{"npm_dependencies":["sonner"],"env_vars_required":[],"ai_rules":["Always implement all 5 components together","Do NOT call feedback functions directly — let RefreshCoordinator manage visual state","SessionCommander is a singleton — never instantiate multiple instances"]}'::jsonb
);

-- Insert Token Manager Architecture Guide
INSERT INTO vault_modules (
  user_id, title, slug, description, domain, module_type, language, tags, code,
  why_it_matters, usage_hint, code_example, source_project, validation_status,
  visibility, difficulty, estimated_minutes, module_group, implementation_order,
  related_modules, solves_problems, common_errors, test_code, context_markdown,
  ai_metadata
) VALUES (
  '82f6649d-f8d6-4da3-9704-d69b2f37d1a1',
  'Token Manager Architecture Guide — FSM-Based Auth Token Lifecycle System',
  'token-manager-architecture-guide',
  'Architecture guide explaining how the 8 components of the Token Manager system (FSM, Service, UnifiedService, Heartbeat, CrossTabLock, Persistence, Types, barrel) integrate into a complete auth token lifecycle management architecture.',
  'architecture',
  'architecture_doc',
  'typescript',
  ARRAY['token-manager','architecture-guide','fsm','finite-state-machine','auth','token-lifecycle','cross-tab','heartbeat','persistence','state-machine'],
  E'/**\n * Token Manager Architecture Guide\n *\n * SYSTEM OVERVIEW:\n * The Token Manager is a FSM-based system managing the complete lifecycle\n * of authentication tokens. Impossible states cannot exist through explicit\n * state transitions and discriminated unions.\n *\n * COMPONENT MAP (8 files):\n *\n * Token Manager System (index.ts — Barrel exports)\n *   ├── Types (types.ts) — TokenState(6), TokenEvent(9), TokenContext, TOKEN_TIMING\n *   ├── Machine (machine.ts) — transition(state, event) → nextState | null\n *   ├── Service (service.ts) — FSM wrapper with side effects, heartbeat, subscribers\n *   ├── UnifiedService (unified-service.ts) — Singleton facade: isAuthenticated(), refreshToken(), etc.\n *   ├── Persistence (persistence.ts) — localStorage adapter for auth STATE (not tokens)\n *   ├── Heartbeat (heartbeat.ts) — Periodic expiry checker, emits TIMER_NEAR_EXPIRY/EXPIRED\n *   ├── CrossTabLock (cross-tab-lock.ts) — BroadcastChannel + localStorage fallback\n *   └── Barrel (index.ts) — Public API surface\n *\n * STATE MACHINE (6 states, 9 events):\n *\n *   idle ──LOGIN_SUCCESS──▶ authenticated\n *                               │\n *                    TIMER_NEAR_EXPIRY\n *                               ▼\n *                           expiring ──REFRESH_START──▶ refreshing\n *                                                        │       │\n *                                              REFRESH_SUCCESS  REFRESH_FAILED\n *                                                   │              │\n *                                            authenticated    expired/error\n *\n *   Any state ──LOGOUT/CLEAR──▶ idle\n *\n * KEY DECISIONS:\n * 1. NO XState dependency — Pure TypeScript FSM with transition table\n * 2. Tokens in httpOnly cookies — Only AUTH STATE in localStorage\n * 3. Heartbeat as fallback — Primary monitoring via SessionCommander\n * 4. UnifiedService as facade — Single entry point for all auth ops\n */\n\nimport { isAuthenticated, refreshToken, clearAuth, setAuthenticated, subscribeToAuth } from ''@/lib/token-manager'';\n\n// Check auth (synchronous)\nif (isAuthenticated()) { /* valid session */ }\n\n// Subscribe to state changes\nconst unsub = subscribeToAuth((state, ctx) => {\n  console.log(''Auth:'', state, ''Expires:'', ctx.expiresAt);\n});\n\n// After login\nsetAuthenticated(14400); // 4h in seconds\n\n// Logout\nclearAuth();',
  'Without a formal state machine, auth state devolves into tangled boolean flags (isLoggedIn, isRefreshing, hasError, isExpired) creating impossible combinations and race conditions. The FSM makes illegal states unrepresentable: you cannot be simultaneously refreshing and idle, or authenticated with null expiresAt. The transition table serves as living documentation — every possible state change is visible in one function.',
  'Use when building any SaaS with robust token lifecycle management. Pairs with session-commander-architecture-guide — Token Manager owns STATE, Session Commander owns COORDINATION.',
  E'// FSM transition (core pattern):\nimport { transition, INITIAL_STATE, INITIAL_CONTEXT } from ''@/lib/token-manager/machine'';\n\nlet state = INITIAL_STATE; // idle\nlet context = INITIAL_CONTEXT;\n\nconst r1 = transition(state, { type: ''LOGIN_SUCCESS'', expiresIn: 14400 }, context);\nif (r1) {\n  state = r1.nextState;     // authenticated\n  context = r1.nextContext; // { expiresAt: Date.now() + 14400000, ... }\n}\n\n// State predicates:\nimport { canMakeApiCalls } from ''@/lib/token-manager/machine'';\nconsole.log(canMakeApiCalls(''authenticated'')); // true\nconsole.log(canMakeApiCalls(''expired''));        // false',
  'risecheckout',
  'validated',
  'global',
  'advanced',
  180,
  'token-manager',
  0,
  ARRAY['0d687429-0f6c-4c74-a46f-26b3f36fa1dd','be66ea5d-fc3b-4a3c-86fe-bf889719de65','aab502c7-22a2-4d44-8b96-2d01cf5e8a67','4c02c917-bc31-4040-9350-963ea9d73f45']::uuid[],
  ARRAY['boolean flag spaghetti for auth state','impossible auth states (refreshing + idle)','race conditions in token refresh','how to implement FSM without XState','token lifecycle management architecture','where to store auth state vs tokens'],
  '[{"error":"transition() returns null","cause":"Invalid state+event combination — FSM rejected illegal transition","fix":"Check transition table in machine.ts. Event is not valid for current state."},{"error":"Token appears expired immediately after login","cause":"expiresIn passed in milliseconds instead of seconds","fix":"LOGIN_SUCCESS expects expiresIn in SECONDS. FSM multiplies by 1000 internally."},{"error":"Auth state lost after page refresh","cause":"Persistence layer not restoring state on mount","fix":"Call restoreTokenState() in AuthProvider initialization before any auth checks"}]'::jsonb,
  E'import { transition, INITIAL_STATE, INITIAL_CONTEXT, canMakeApiCalls } from ''@/lib/token-manager/machine'';\n\nconst r1 = transition(''idle'', { type: ''LOGIN_SUCCESS'', expiresIn: 3600 }, INITIAL_CONTEXT);\nassert(r1 !== null, ''LOGIN_SUCCESS from idle should succeed'');\nassert(r1.nextState === ''authenticated'');\nassert(r1.nextContext.expiresAt !== null);\n\nconst r2 = transition(''idle'', { type: ''REFRESH_START'' }, INITIAL_CONTEXT);\nassert(r2 === null, ''REFRESH_START from idle should be rejected'');\n\nassert(canMakeApiCalls(''authenticated'') === true);\nassert(canMakeApiCalls(''expired'') === false);',
  E'## Overview\n\nThe Token Manager is a FSM-based architecture for managing authentication token lifecycles in SaaS applications. Replaces ad-hoc boolean flag management with deterministic, type-safe state machine.\n\n## How it Works\n\n8 files in layered architecture:\n1. **Types** — Discriminated unions for TokenState (6 states), TokenEvent (9 events), TokenContext, timing constants.\n2. **Machine** — Pure transition function: (state, event, context) → {nextState, nextContext} | null. Plus predicates: canMakeApiCalls, needsRefresh, isExpired.\n3. **Service** — FSM wrapper with side effects: persistence, heartbeat, subscriber notification.\n4. **UnifiedService** — Singleton facade: isAuthenticated(), refreshToken(), clearAuth(), setAuthenticated(), subscribeToAuth().\n5. **Persistence** — localStorage adapter for auth STATE (not tokens). Tokens in httpOnly cookies.\n6. **Heartbeat** — Periodic timer checking token expiry, emitting FSM events.\n7. **CrossTabLock** — BroadcastChannel + localStorage fallback preventing concurrent refresh.\n8. **Barrel** — Public API surface with selective re-exports.\n\n## When to Use\n- SaaS with JWT/cookie auth and expiring tokens\n- When deterministic auth state management is needed\n- Multi-tab applications\n\n## When NOT to Use\n- Simple session-only auth (no refresh tokens)\n- SSR apps where auth is server-managed\n- Apps using third-party auth SDKs (Auth0, Firebase Auth)\n\n## Performance\n- FSM transition is O(1) — pure switch/case\n- Heartbeat interval: 60s (configurable)\n- Persistence writes debounced via Service layer\n- CrossTabLock: BroadcastChannel (zero-copy) with localStorage polling fallback',
  '{"npm_dependencies":[],"env_vars_required":[],"ai_rules":["NEVER store actual tokens in localStorage — only auth STATE","transition() is PURE — no side effects. Side effects belong in Service layer","Always pair with Session Commander for production use"]}'::jsonb
);